name: Release Krakend helm chart

on:
  push:
    tags:
      - '*.*.*'

jobs:
  # release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout tag
  #       uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.ref }}

  gh-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

